version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGODB_USERNAME: max
    env_file:
      - env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  data:
  logs:
