apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: starcraftman/k8:11
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"