GET http://localhost:8080/feed/posts

####

POST  http://localhost:8080/feed/post HTTP/1.1
content-type: application/json

{
    "title": "Simp",
    "Content": "Hello world"
}

####
POST  http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "password": "testing"
}