apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  hostPath:
    path: /tmp/test
    type: DirectoryOrCreate
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle